Dz2 Ilin D.
otopba/students_homework pull request #14
Opened 2019-02-28 15:49 UTC by dmiln

2019-02-28 21:08 UTC, otopba requested changes
Задание сделано хорошо, нужно поправить небольшие замечания что оставлены к коду.
Общие замечания:
1) Нет выделение активного элемента в RecyclerView 
2) Если выделить студента, потом нажать добавить, далее сохранить, новый студент не создается.
3) Если ввести очень длинное имя, верстка расползается

2019-02-28 21:08 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/students/MainActivity.java
> +        genderCheckBox = findViewById(R.id.main_activity__checkbox_gender);
Где-то activity_main, а где-то main_activity

2019-02-28 21:08 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/students/MainActivity.java
> +    private int currentImageId;
Если есть поле selectedStudent, зачем поле currentImageId?

2019-02-28 21:08 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/students/MainActivity.java
> +    private void setVisibilityBottomElements(int visible) {
Этот элемент можно было бы заменить Group. _Можно не изменять_

2019-02-28 21:08 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/students/MainActivity.java
> +        int i = firstNameEditText.getText().toString().length();
1) i и j можно использовать для циклов, но в других местах названия переменных должны нести больше смысла
2) firstNameEditText.getText() может вернуть null

2019-02-28 21:08 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/students/MainActivity.java
> +        boolean g = genderCheckBox.isChecked();
Названия переменных должны нести больше смысла

2019-02-28 21:08 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/students/Student.java
> +import java.io.Serializable;
Лишний импорт

2019-02-28 21:08 UTC, otopba commented on app/src/main/res/layout-v16/student_item.xml
> +<?xml version="1.0" encoding="utf-8"?>
Можно было обойтись одной версией лейаута =)

2019-02-28 21:08 UTC, otopba commented on app/src/main/res/layout/activity_main.xml
> +        <LinearLayout
Если используешь констрейнт, то нужно по максимуму избегать вложенности. Тут можно обойтись без этого LinearLayout

2019-03-01 15:27 UTC, dmiln commented on app/src/main/java/ru/ok/technopolis/students/MainActivity.java
> +    private int currentImageId;
Поле currentImageId нужно, потому что, если начать редактировать информацию о существующем студенте, можно поменять аватар и записать существующего студента уже с новым аватаром

2019-03-01 15:29 UTC, dmiln commented
Исправил замечания

2019-03-04 21:40 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/students/MainActivity.java
> +    private int currentImageId;
Все равно это значение можно записать в selectedStudent

2019-03-04 21:44 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/students/MainActivity.java
> +    private int imageIdInAvatarField;
Название стало еще более непонятным

2019-03-04 21:44 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/students/MainActivity.java
> +        if (firstNameEditText.getText() == null || secondNameEditText.getText() == null) {
Можно использовать TextUtils.isEmpty()

2019-03-04 21:44 UTC, otopba commented on app/src/main/res/layout/activity_main.xml
> +            app:constraint_referenced_ids="activity_main__separated_line,activity_main__save_button,activity_main__student_title,activity_main__student_avatar,activity_main__second_name,activity_main
Лучше не делать такие длинные строки. Разделяй энтером

2019-03-04 21:44 UTC, otopba commented
Работа принята.
9 балов

2024-12-09 20:14 UTC, closed without merging