Students | Kovshov | Demo
otopba/students_homework pull request #19
Opened 2019-02-28 23:56 UTC by prohladenn

2019-03-03 20:36 UTC, otopba requested changes
Задание сделано хорошо, нужно поправить небольшие замечания что оставлены к коду.
Общие замечания:
1) Не очень удобно что в случае когда одно из полей пустое, сбрасывается полностью весь ввод

2019-03-03 20:36 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/students/MainActivity.java
> +    List<Student> students;
Лучше явно указывать видимость

2019-03-03 20:36 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/students/MainActivity.java
> +            if (name.getText().toString().isEmpty())
Без фигурных скобок тяжеловато читать

2019-03-03 20:36 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/students/MainActivity.java
> +            else if (surname.getText().toString().isEmpty())
surname.getText() иногда возвращает null

2019-03-03 20:36 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/students/Student.java
> +class Student {
Аналогично про видимость

2019-03-03 20:36 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/students/StudentAdapter.java
> +
Лишняя строка

2019-03-03 20:36 UTC, otopba commented on app/src/main/res/layout/activity_main.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
1) Вложенность доходит до 3х. Лучше когда 1-2 можно упростить иерархию
2) Используется привязка left/right. Лучше start/end

2019-03-27 09:41 UTC, prohladenn commented on app/src/main/res/layout/activity_main.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
Убрал ненужный Linear, теперь вложенность не больше 2х

2019-03-27 09:41 UTC, prohladenn commented on app/src/main/java/ru/ok/technopolis/students/StudentAdapter.java
> +
Убрал

2019-03-27 09:41 UTC, prohladenn commented on app/src/main/java/ru/ok/technopolis/students/Student.java
> +class Student {
Добавил

2019-03-27 09:41 UTC, prohladenn commented on app/src/main/java/ru/ok/technopolis/students/MainActivity.java
> +            else if (surname.getText().toString().isEmpty())
Теперь никогда такого не произойдёт

2019-03-27 09:41 UTC, prohladenn commented on app/src/main/java/ru/ok/technopolis/students/MainActivity.java
> +            if (name.getText().toString().isEmpty())
Добавил их

2019-03-27 09:42 UTC, prohladenn commented on app/src/main/java/ru/ok/technopolis/students/MainActivity.java
> +    List<Student> students;
Указал

2019-03-27 09:42 UTC, prohladenn commented
> Задание сделано хорошо, нужно поправить небольшие замечания что оставлены к коду.
> Общие замечания:
> 
> 1. Не очень удобно что в случае когда одно из полей пустое, сбрасывается полностью весь ввод

Главное замечание исправлено!

2019-03-27 20:59 UTC, otopba commented on app/src/main/res/layout/activity_main.xml
> +            app:layout_constraintLeft_toRightOf="@+id/main_card_avatar"
По прежнему привязка left-right. Лучше start-end

2019-03-27 20:59 UTC, otopba commented
Работа принята
10 балов

2019-04-08 13:37 UTC, closed without merging