homework
otopba/students_homework pull request #26
Opened 2019-04-21 15:06 UTC by JustAddAcid

2019-04-21 20:37 UTC, otopba requested changes
Работа выполнена хорошо. Небольшие замечания

2019-04-21 20:37 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/students/MainActivity.java
> +    private static final String BOTTOM_SHEET_TAG = "BOTTOM_SHEET";
Обычно тег делают паблик и определяют у самого фрагмента

2019-04-21 20:37 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/students/bottom_sheet_fragment/StudentBottomSheet.java
> +    public void onDetach() {
Зачем?

2019-04-21 20:37 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/students/bottom_sheet_fragment/StudentBottomSheet.java
> +            else {
`else` пишется на той же строке, что и закрывающаяся скобка

2019-04-21 20:37 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/students/bottom_sheet_fragment/StudentBottomSheet.java
> +                    Toast.makeText(getActivity(), "Please, fill all the fields", Toast.LENGTH_LONG).show();
Строки лучше поместить в strings

2019-04-21 20:37 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/students/bottom_sheet_fragment/StudentBottomSheet.java
> +                if(firstNameEditText.getText().toString().equals("") || secondNameEditText.getText().toString().equals("")){
`firstNameEditText.getText()` иногда может возвращать null

2019-04-21 20:37 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/students/model/Student.java
> +    public Student(String firstName, String secondName, boolean maleGender, int photo) {
Зачем этот конструктор?

2019-04-21 20:37 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/students/model/Student.java
> +        id = UUID.randomUUID();
Если у тебя есть уникальный id, то в адаптере можно ставить тег не целиком класс, а только его id

2019-04-21 20:37 UTC, otopba commented on app/src/main/res/layout/student__bottom_sheet.xml
> +<?xml version="1.0" encoding="utf-8"?>
Почему в имени файла двойное подчеркивание?

2019-04-21 20:37 UTC, otopba commented on app/src/main/res/layout/student__bottom_sheet.xml
> +    <LinearLayout
Можно обойтись без этого лейаута

2019-04-21 20:37 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/students/model/Student.java
> +public class Student implements Serializable {
1) Зачем тут `Serializable`? 
2) Удали `ru.ok.technopolis.students.Student`

2019-04-24 21:03 UTC, JustAddAcid commented
Поправил

2019-04-24 21:06 UTC, JustAddAcid commented on app/src/main/java/ru/ok/technopolis/students/bottom_sheet_fragment/StudentBottomSheet.java
> +                if(firstNameEditText.getText().toString().equals("") || secondNameEditText.getText().toString().equals("")){
Посмотрел в документации: ничего про явное возвращение null в .getText() не сказано. 
Я правильно понимаю, что в этой ситуации могу упереться в NullPointerException только в том случае, если firstNameEditText и/или secondNameEditText будет каким-то образом == null?
На всякий случай, обернул в if(){}

2019-04-29 20:30 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/students/bottom_sheet_fragment/StudentBottomSheet.java
> +                if(firstNameEditText.getText().toString().equals("") || secondNameEditText.getText().toString().equals("")){
![image](https://user-images.githubusercontent.com/4225279/56924931-cd372680-6ad6-11e9-9a1b-36f32965135d.png)

2019-04-29 20:37 UTC, otopba requested changes

2019-04-29 20:37 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/students/model/Student.java
> +public class Student  {
Стоит удалить старый класс ru.ok.technopolis.students.Student

2019-04-29 20:37 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/students/bottom_sheet_fragment/StudentBottomSheet.java
> +package ru.ok.technopolis.students.bottom_sheet_fragment;
Названия пакетов не пишутся через подчеркивания

2019-04-29 20:37 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/students/bottom_sheet_fragment/StudentBottomSheet.java
> +    private static final String STUDENT_TAG_ID = "STUDENT_TAG_ID";
Это не тег. Это аргумент. Можно делать названия в стиле STUDENT_ID_ARG STUDENT__ID_EXTRA и тп

2019-04-29 20:37 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/students/bottom_sheet_fragment/StudentBottomSheet.java
> +        else {
else пишется на той же строке

2019-04-29 20:37 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/students/dao/StudentsPhotoDAO.java
> +    private List <Integer> femalePhotos;
можно сделать final

2019-04-29 20:38 UTC, otopba commented
Работа принята
10 балов

2019-06-16 15:19 UTC, closed without merging