Druzhinin HomeWork
otopba/students_homework pull request #5
Opened 2019-02-26 00:09 UTC by senyast4745

2019-03-03 19:25 UTC, otopba requested changes
1) Проект не компилируется
2) Пожалуйста, удали из репозитория папку .idea. Это моя изначальная ошибка. Можно забрать изменения из моего репозитория, там исправлена эта проблема

2019-03-04 21:55 UTC, otopba commented
@senyast4745 
1) Проект по прежнему не компилируется. Нет ресурса drawable/male_4
2) Не удалена папка .idea

2019-03-05 21:20 UTC, otopba requested changes
Нужно поправить замечания что оставлены к коду.
Общие замечания:
1) Нет выделение активного элемента в RecyclerView
2) Очень длинное имя ломает верстку
3) Файлы male_X и female_X не используются

2019-03-05 21:20 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/students/DataBaseHandler.java
> +        //DATABASE_PATH = context.getApplicationInfo().dataDir + "/databases/";
Зачем этот комментарий?

2019-03-05 21:20 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/students/DataBaseHandler.java
> +
Следи за пустыми строками

2019-03-05 21:20 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/students/DataBaseHandler.java
> +        if(LOG)
Лучше всегда ставить фигурные скобки

2019-03-05 21:20 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/students/DataBaseHandler.java
> +            Log.d(LOG_TAG, "Student infomation " + student.getFirstName() + " " + student.getSecondName() + " " + student.isMaleGender() + " " + student.getPhoto());
Опечатка в слове "infomation" =)

2019-03-05 21:20 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/students/DataBaseHandler.java
> +        String seletQuery = "SELECT * FROM " + TABLE_STUDENTS;
seletQuery -> selectQuery

2019-03-05 21:20 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/students/DataBaseHandler.java
> +import org.jetbrains.annotations.Nullable;
Почему решил использовать аннотации не андроида а джет брейнса?

2019-03-05 21:20 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/students/IDataBaseHendler.java
> +public interface IDataBaseHendler {
Hendler -> Handler

Я не сторонник префикса I перед названием интерфеса. По мне так лучше уже полностью DataBaseHandlerInterface. Но это на вкус и цвет

2019-03-05 21:20 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/students/MainActivity.java
> +
Следи за пустыми строками

2019-03-05 21:20 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/students/MainActivity.java
> +    private List<Student> generateStudentList(){
Бесполезный метод, вызывается 1 раз и создает пустой список

2019-03-05 21:20 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/students/MainActivity.java
> +    private boolean VISIBILITY_LAYOUTS = false;
капсом указываются константы, VISIBILITY_LAYOUTS это переменная

2019-03-05 21:20 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/students/MainActivity.java
> +            //Log.d(BuildConfig.LOG_TAG, "Check delete " + dbHandler.getStudent(student.getID()).getFirstName());
?

2019-03-05 21:20 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/students/MainActivity.java
> +            int indexArr = students.indexOf(student);
можно просто index

2019-03-05 21:20 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/students/MainActivity.java
> +    private void onSaveClick(Student student, String name, String lastname, boolean gender){
После закрытой скобки стоит ставить пробел
boolean gender){ 
->
boolean gender) {

2019-03-05 21:20 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/students/MainActivity.java
> +            Toast.makeText(MainActivity.this, "Ошибка, введите имя и фамилию", Toast.LENGTH_SHORT).show();
Можно просто this

2019-03-05 21:20 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/students/MainActivity.java
> +                Log.d(BuildConfig.LOG_TAG, "UI Updated");
Тег для логов нужен что бы понимать какой класс пишет логи, не стоит использовать один тег для всего проекта

2019-03-05 21:20 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/students/MainActivity.java
> +    protected void onDestroy() {
Зачем это переопределение?

2019-03-05 21:20 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/students/MainActivity.java
> +        Button deliteButton = findViewById(R.id.main_activity_button_delete);
deliteButton -> deleteButton

2019-03-05 21:20 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/students/Student.java
> -public class Student {
Почему больше не паблик?

2019-03-05 21:20 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/students/Student.java
> +    private int _id;
В джаве так не пишут. Просто id

2019-03-05 21:20 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/students/Student.java
> +        this._id = _id;
В этом конструкторе можно вызвать следующий, что бы не дублировать присвоение полей

2019-03-05 21:20 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/students/StudentAdapter.java
> +    private Listener onItemClickListner;
onItemClickListner -> onItemClickListener

2019-03-05 21:20 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/students/StudentAdapter.java
> +            if(BuildConfig.LOG)
Фигурные скобки

2019-03-05 21:20 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/students/StudentAdapter.java
> +
Пустые строки

2019-03-05 21:20 UTC, otopba commented on app/src/main/res/drawable/shadow_add_button.xml
> +<?xml version="1.0" encoding="utf-8"?>
Зачем этот файл?

2019-03-05 21:20 UTC, otopba commented on app/src/main/res/layout/activity_main.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
Очень большая вложенность лейаутов, нужно сокращать. Лучше что бы было не более двух уровней вложенности

2019-03-05 21:20 UTC, otopba commented on app/src/main/res/layout/activity_main.xml
> +
Пустые строки

2019-03-05 21:20 UTC, otopba commented on app/src/main/res/layout/students_item.xml
> +
Пустые строки

2019-03-05 21:20 UTC, otopba commented on app/src/main/res/values/strings.xml
> +    <string name="profilephot">ProfilePhot</string>
profilephot-> profile_photo

2019-03-06 11:10 UTC, senyast4745 commented on app/src/main/java/ru/ok/technopolis/students/DataBaseHandler.java
> +        //DATABASE_PATH = context.getApplicationInfo().dataDir + "/databases/";
Это рудименты эксперимента с бд. Поправлю

2019-03-06 11:11 UTC, senyast4745 commented on app/src/main/java/ru/ok/technopolis/students/DataBaseHandler.java
> +
Я же на моменте приема в бд уже все ненужное отсеиваю

2019-03-06 11:11 UTC, senyast4745 commented on app/src/main/java/ru/ok/technopolis/students/DataBaseHandler.java
> +        //DATABASE_PATH = context.getApplicationInfo().dataDir + "/databases/";
Если ты про то, что мне в бд может что то не валидное прийти

2019-03-06 11:12 UTC, senyast4745 commented on app/src/main/java/ru/ok/technopolis/students/DataBaseHandler.java
> +        if(LOG)
А где я не поставил?  Не вижу

2019-03-06 11:13 UTC, senyast4745 commented on app/src/main/java/ru/ok/technopolis/students/DataBaseHandler.java
> +            Log.d(LOG_TAG, "Student infomation " + student.getFirstName() + " " + student.getSecondName() + " " + student.isMaleGender() + " " + student.getPhoto());
С английским всё плохо. Пофиксим

2019-03-06 11:14 UTC, senyast4745 commented on app/src/main/java/ru/ok/technopolis/students/IDataBaseHendler.java
> +public interface IDataBaseHendler {
Хорошо. Я просто привык к префикс. Учту

2019-03-06 11:15 UTC, senyast4745 commented on app/src/main/java/ru/ok/technopolis/students/MainActivity.java
> +                Log.d(BuildConfig.LOG_TAG, "UI Updated");
Понял

2019-03-06 11:18 UTC, senyast4745 commented on app/src/main/java/ru/ok/technopolis/students/MainActivity.java
> +            //Log.d(BuildConfig.LOG_TAG, "Check delete " + dbHandler.getStudent(student.getID()).getFirstName());
А что тут не так? (

2019-03-06 11:19 UTC, senyast4745 commented on app/src/main/java/ru/ok/technopolis/students/MainActivity.java
> +            Toast.makeText(MainActivity.this, "Ошибка, введите имя и фамилию", Toast.LENGTH_SHORT).show();
Где можно просто this?

2019-03-06 11:20 UTC, senyast4745 commented on app/src/main/java/ru/ok/technopolis/students/Student.java
> +        this._id = _id;
Окей

2019-03-06 11:21 UTC, senyast4745 commented on app/src/main/res/layout/activity_main.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
Хорошо. Подумаю как

2019-03-06 11:22 UTC, senyast4745 commented on app/src/main/java/ru/ok/technopolis/students/Student.java
> -public class Student {
Мне хватает пакетной видимости

2019-03-08 12:22 UTC, senyast4745 commented on app/src/main/res/drawable/shadow_add_button.xml
> +<?xml version="1.0" encoding="utf-8"?>
это тень под кнопочкой под главной

2019-03-09 09:45 UTC, otopba commented on app/src/main/res/drawable/shadow_add_button.xml
> +<?xml version="1.0" encoding="utf-8"?>
Но этот файл не используется

2019-03-09 09:48 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/students/DataBaseHandler.java
> +
Речь про пустые строки в коде.

2019-03-09 09:48 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/students/DataBaseHandler.java
> +        if (LOG) {
Фигурные скобки

2019-03-09 09:48 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/students/DataBaseHandler.java
> +        if (student.isMaleGender())
Фигурные скобки

2019-03-09 09:48 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/students/MainActivity.java
> +
Пустая строка

2019-03-09 09:48 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/students/MainActivity.java
> +            /*int pos = students.indexOf(student);
Зачем добавлен этот закомментированный код?

2019-03-09 09:49 UTC, otopba commented
Работа принята.
8 балов

2019-03-13 03:30 UTC, senyast4745 commented on app/src/main/java/ru/ok/technopolis/students/DataBaseHandler.java
> +        //DATABASE_PATH = context.getApplicationInfo().dataDir + "/databases/";
Fixed

2019-03-13 03:30 UTC, senyast4745 commented on app/src/main/java/ru/ok/technopolis/students/DataBaseHandler.java
> +
Fixed

2019-03-13 03:31 UTC, senyast4745 commented on app/src/main/java/ru/ok/technopolis/students/DataBaseHandler.java
> +        if(LOG)
Fixed

2019-03-13 03:32 UTC, senyast4745 commented on app/src/main/java/ru/ok/technopolis/students/DataBaseHandler.java
> +            Log.d(LOG_TAG, "Student infomation " + student.getFirstName() + " " + student.getSecondName() + " " + student.isMaleGender() + " " + student.getPhoto());
Fixed

2019-03-13 03:32 UTC, senyast4745 commented on app/src/main/java/ru/ok/technopolis/students/DataBaseHandler.java
> +        String seletQuery = "SELECT * FROM " + TABLE_STUDENTS;
Fixed

2019-03-13 03:33 UTC, senyast4745 commented on app/src/main/res/drawable/shadow_add_button.xml
> +<?xml version="1.0" encoding="utf-8"?>
Fixed

2019-03-13 03:33 UTC, senyast4745 commented on app/src/main/res/layout/activity_main.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
Fixed

2019-03-13 03:34 UTC, senyast4745 commented on app/src/main/res/layout/activity_main.xml
> +
Fixed

2019-03-13 03:34 UTC, senyast4745 commented on app/src/main/java/ru/ok/technopolis/students/DataBaseHandler.java
> +        if (LOG) {
Fixed

2019-03-13 03:34 UTC, senyast4745 commented on app/src/main/res/layout/students_item.xml
> +
Fixed

2019-03-13 03:34 UTC, senyast4745 commented on app/src/main/res/values/strings.xml
> +    <string name="profilephot">ProfilePhot</string>
Fixed

2019-03-13 03:35 UTC, senyast4745 commented on app/src/main/java/ru/ok/technopolis/students/DataBaseHandler.java
> +        if (student.isMaleGender())
Fixed

2019-03-13 03:36 UTC, senyast4745 commented on app/src/main/java/ru/ok/technopolis/students/MainActivity.java
> +
Fixed

2019-03-13 03:36 UTC, senyast4745 commented on app/src/main/java/ru/ok/technopolis/students/MainActivity.java
> +            /*int pos = students.indexOf(student);
Fixed

2019-03-14 21:52 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/students/StudentAdapter.java
> +            //position.setActive(true);
лишний коммент

2019-03-14 21:53 UTC, otopba commented
Работа принята.
9 балов

2020-05-19 21:36 UTC, closed without merging